apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: pro-eventos
spec:
  selector:
    app: backend-deployment
  ports:
    - name: backend-service
      nodePort: 32120 #externo
      port: 80 #service
      targetPort: 80 #pod
  type: NodePort
