apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pro-eventos
spec:
  selector:
    app: frontend-deployment
  ports:
    - name: frontend-service
      nodePort: 32121 #externo
      port: 8080 #service
      targetPort: 80 #pod
  type: NodePort
