apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: 'pro-eventos'
spec:
  selector:
    app: frontend-deployment
  ports:
    - name: "http"
      nodePort: 32123 #externo
      port: 8080 #service
      targetPort: 80 #pod
  type: NodePort
