apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: 'pro-eventos'
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend-container
        image: giov3nn10/proeventos-backend:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
