apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: 'pro-eventos'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend-container
        image: giov3nn10/proeventos-frontend:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
