apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-management-deployment
  namespace: pro-eventos
spec:
  selector:
    matchLabels:
      app: db-management-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: db-management-deployment
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
