apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: pro-eventos
spec:
  selector:
    matchLabels:
      app: postgres-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_PASSWORD
              value: admin
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc
