apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: 'pro-eventos'
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend
        image: giov3nn10/proeventos-backend:latest
        ports:
        - containerPort: 80
